//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Donate4Life
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donors()
        {
            this.UsersFavourites = new HashSet<UsersFavourites>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string EyeColor { get; set; }
        public string HairColor { get; set; }
        public int Age { get; set; }
        public int Kilos { get; set; }
        public int Height { get; set; }
        public string Town { get; set; }
        public System.DateTime AddedDate { get; set; }
        public int Views { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersFavourites> UsersFavourites { get; set; }
    }
}
